const express = require("express")
 const router = express.Router()
 const userController = require("../controllers/userController")
 const verifyJWT = require("../middleware/verifyJWT")
 router.use(verifyJWT)
 router.get("/",userController.getAllUsers)
 router.get("/:id", userController.getUserById)
 router.delete("/",userController.deleteUser)
 router.put("/",userController.updateUser)
 module.exports = router